#cloud-config
write_files:
  - path: /etc/netplan/eth1.yaml
    content: |
      network:
        version: 2
        ethernets:
          eth1:
            dhcp4: true
runcmd:
  - netplan apply
  - /sbin/sysctl net.ipv4.conf.all.forwarding=1
