cephClusterSpec:
    mgr:
      limits:
        cpu: "200m"
        memory: "1Gi"
      requests:
        cpu: "50m"
        memory: "500Mi"
    mon:
      limits:
        cpu: "200m"
        memory: "2Gi"
      requests:
        cpu: "50m"
        memory: "1Gi"
    osd:
      limits:
        cpu: "400m"
        memory: "3Gi"
      requests:
        cpu: "200m"
        memory: "1.5Gi"
    crashcollector:
      limits:
        cpu: "10m"
        memory: "60Mi"
      requests:
        cpu: "1m"
        memory: "15Mi"
    prepareosd:
      # limits: It is not recommended to set limits on the OSD prepare job
      #         since it's a one-time burst for memory that must be allowed to
      #         complete without an OOM kill.  Note however that if a k8s
      #         limitRange guardrail is defined external to Rook, the lack of
      #         a limit here may result in a sync failure, in which case a
      #         limit should be added.  1200Mi may suffice for up to 15Ti
      #         OSDs ; for larger devices 2Gi may be required.
      #         cf. https://github.com/rook/rook/pull/11103
      requests:
        cpu: "500m"
        memory: "50Mi"
# Defaults, haven't checked usage
    mgr-sidecar:
      limits:
        cpu: "500m"
        memory: "100Mi"
      requests:
        cpu: "100m"
        memory: "40Mi"
    logcollector:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    cleanup:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "100Mi"
    exporter:
      limits:
        cpu: "50m"
        memory: "50Mi"
      requests:
        cpu: "10m"
        memory: "10Mi"
