helmDefaults:
  timeout: 600
  createNamespace: false
  skipDeps: true

# environments:
#   service:
#     missingFileHandler: Error
#     values:
#     - {{ requiredEnv "CK8S_CONFIG_PATH" }}/rook-ceph/values.yaml

#   workload:
#     missingFileHandler: Error
#     values:
#     - {{ requiredEnv "CK8S_CONFIG_PATH" }}/rook-ceph/values.yaml
    # secrets:
    # - {{ requiredEnv "CK8S_CONFIG_PATH" }}/rook-ceph/secret/secrets.yaml

---

releases:
- name: rook-ceph-crds
  namespace: rook-ceph
  labels:
    app: rook-ceph-crds
  chart: ./chart/rook-ceph-crds
  version: 0.0.1
  missingFileHandler: Error

- name: rook-ceph-operator
  namespace: rook-ceph
  labels:
    app: rook-ceph-operator
  chart: ./upstream/rook-ceph
  version: 0.0.1
  needs:
  - rook-ceph/rook-ceph-crds
  missingFileHandler: Error
  values:
  - values/rook-ceph/rook-ceph-operator.yaml.gotmpl

- name: rook-ceph-cluster
  namespace: rook-ceph
  labels:
    app: rook-ceph-cluster
    cluster:
  chart: ./upstream/rook-ceph-cluster
  version: 0.0.1
  needs:
  - rook-ceph/rook-ceph-operator
  missingFileHandler: Error
  values:
  - values/rook-ceph/rook-ceph-cluster.yaml.gotmpl
  - values/cluster-presets/{{ .Values.clusterPreset }}.yaml
