- name: Worker cis benchmark patch
  hosts: kube_node
  become: yes  # This allows the playbook to run with sudo privileges

  tasks:
    - name: 4.1.1 Ensure that the kubelet service file permissions are set to 600 or more restrictive
      become: yes  # Ensure the task runs with sudo privileges
      command: chmod -R 600 /etc/systemd/system/kubelet.service
    - name: 4.1.7 Ensure that the certificate authorities file permissions are set to 600 or more restrictive
      become: yes  # Ensure the task runs with sudo privileges
      command: chmod -R 600 /etc/kubernetes/ssl/ca.crt
    - name: 4.1.9 If the kubelet config.yaml configuration file is being used validate permissions set to 600 or more restrictive
      become: yes  # Ensure the task runs with sudo privileges
      command: chmod -R 600 /etc/kubernetes/kubelet-config.yaml
    - name: 4.2.7 Ensure that the --hostname-override argument is not set
      become: yes  # Ensure the task runs with sudo privileges
      shell: |
        sed -i '/^                $KUBELET_HOSTNAME/d' /etc/systemd/system/kubelet.service && sed -i '/^KUBELET_HOSTNAME/d' /etc/kubernetes/kubelet.env && systemctl daemon-reload && systemctl restart kubelet.service
